- name: -redis- Create the path which the redis need. 
  file: 
    path: "{{ item }}"
    state: directory
  loop: 
    - /etc/redis
    - /data
    - /var/log/redis 
- name: -redis- 创建主节点配置文件
  template: src=master.conf.j2 dest=/etc/redis/master.conf
- name: -redis- 创建从节点1配置文件
  template: src=slave1.conf.j2 dest=/etc/redis/slave1.conf
- name: -redis- 创建从节点2配置文件
  template: src=slave2.conf.j2 dest=/etc/redis/slave2.conf
- name: -redis- 创建sentinel 1 配置文件
  template: src=sentinel1.conf.j2 dest=/etc/redis/sentinel1.conf
- name: -redis- 创建sentinel 2 配置文件
  template: src=sentinel2.conf.j2 dest=/etc/redis/sentinel2.conf
- name: -redis- 创建sentinel 3 配置文件
  template: src=sentinel3.conf.j2 dest=/etc/redis/sentinel3.conf
- name: copy install files to  redis server
  copy: 
    src: ./down/redis/
    dest: /tmp/redis/
- name: -redis- 安装必要工具
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - gcc
    - automake
    - autoconf
    - libtool
    - make
- name: "-redis- 解压redis安装包"
  unarchive:
    src: /tmp/redis/redis-4.0.9.tar.gz 
    dest: /tmp/redis
    remote_src: yes
- name: "execute redis install."
  shell: make && make PREFIX=/usr/local/redis install 
  args:
    chdir: /tmp/redis/redis-4.0.9 
- name: "-redis- 设置redis环境变量."
  shell: "{{ item }}"
  loop: 
    - sed -i '/export/d' ~/.bash_profile 
    - echo "PATH=\$PATH:/usr/local/redis/bin/" >> ~/.bash_profile 
    - echo "export PATH" >> ~/.bash_profile 
    - source ~/.bash_profile 
- name: "-redis- 设置redis开机启动."
  shell: "{{ item }}"
  args:
    chdir: /tmp/redis
  loop: 
    - chmod 760 redis.sh 
    - mv redis.sh /usr/local/bin/
    - mv redis.service /lib/systemd/system/
    - systemctl enable redis.service  
    - systemctl start redis.service  
- name: "-redis- 设置redis防火墙."
  shell: "{{ item }}"
  args:
    chdir: /tmp/redis
  loop: 
    - firewall-cmd --zone=public --add-port={{ REDIS_MATER_PORT }}/tcp --permanent 
    - firewall-cmd --zone=public --add-port={{ REDIS_SLAVE1_PORT }}/tcp --permanent 
    - firewall-cmd --zone=public --add-port={{ REDIS_SLAVE2_PORT }}/tcp --permanent 
    - firewall-cmd --zone=public --add-port={{ REDIS_SENTINEL1_PORT }}/tcp --permanent 
    - firewall-cmd --zone=public --add-port={{ REDIS_SENTINEL2_PORT }}/tcp --permanent 
    - firewall-cmd --zone=public --add-port={{ REDIS_SENTINEL3_PORT }}/tcp --permanent 
    - firewall-cmd --reload

