- debug:
    msg: "start to install redis." 
- name: copy install files to  redis server
  copy: 
    src: ./down/redis/
    dest: /tmp/redis/
- name: install tools for redis
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - gcc
    - automake
    - autoconf
    - libtool
    - make
- name: "unarchive redis file"
  unarchive:
    src: /tmp/redis/4.0.9.tar.gz
    dest: /tmp/redis
    remote_src: yes
- name: "execute redis install."
  shell: make && make PREFIX=/usr/local/redis install 
  args:
    chdir: /tmp/redis/redis-4.0.9 
- name: create the path which the redis need. 
  file: 
    path: "{{ item }}"
    state: directory
  loop: 
    - /etc/redis
    - /data
    - /var/log/redis 
- name: "prepare redis file."
  shell: "{{ item }}"
  args:
    chdir: /tmp/redis
  loop: 
    - sed "s/REDIS_MATER_PORT/{{ REDIS_MATER_PORT }}/g" master_template.conf  > master.conf
    - sed -i "s/REDIS_MATER_IP/{{ REDIS_MATER_IP }}/g" master.conf
    - cp master.conf /etc/redis/
    - sed "s/REDIS_MATER_PORT/{{ REDIS_SLAVE1_PORT }}/g" master_template.conf  > slave1.conf
    - sed -i "s/REDIS_MATER_IP/{{ REDIS_MATER_IP }}/g" slave1.conf
    - echo "slaveof {{ REDIS_MATER_IP }} {{ REDIS_MATER_PORT }}" >> slave1.conf
    - cp slave1.conf /etc/redis/
    - sed "s/REDIS_MATER_PORT/{{ REDIS_SLAVE2_PORT }}/g" master_template.conf  > slave2.conf
    - sed -i "s/REDIS_MATER_IP/{{ REDIS_MATER_IP }}/g" slave2.conf
    - echo "slaveof {{ REDIS_MATER_IP }} {{ REDIS_MATER_PORT }}" >> slave2.conf
    - cp slave2.conf /etc/redis/
    - sed "s/REDIS_MATER_PORT/{{ REDIS_MATER_PORT }}/g" sentinel_template.conf  > sentinel1.conf
    - sed -i "s/REDIS_MATER_IP/{{ REDIS_MATER_IP }}/g" sentinel1.conf
    - sed -i "s/REDIS_SENTINEL1_PORT/{{ REDIS_SENTINEL1_PORT }}/g" sentinel1.conf
    - sed -i "s/QUORUM_NUM/{{ QUORUM_NUM }}/g" sentinel1.conf
    - cp sentinel1.conf /etc/redis/
    - sed "s/REDIS_MATER_PORT/{{ REDIS_MATER_PORT }}/g" sentinel_template.conf  > sentinel2.conf
    - sed -i "s/REDIS_MATER_IP/{{ REDIS_MATER_IP }}/g" sentinel2.conf
    - sed -i "s/REDIS_SENTINEL1_PORT/{{ REDIS_SENTINEL2_PORT }}/g" sentinel2.conf
    - sed -i "s/QUORUM_NUM/{{ QUORUM_NUM }}/g" sentinel2.conf
    - cp sentinel2.conf /etc/redis/
    - sed "s/REDIS_MATER_PORT/{{ REDIS_MATER_PORT }}/g" sentinel_template.conf  > sentinel3.conf
    - sed -i "s/REDIS_MATER_IP/{{ REDIS_MATER_IP }}/g" sentinel3.conf
    - sed -i "s/REDIS_SENTINEL1_PORT/{{ REDIS_SENTINEL3_PORT }}/g" sentinel3.conf
    - sed -i "s/QUORUM_NUM/{{ QUORUM_NUM }}/g" sentinel3.conf
    - cp sentinel3.conf /etc/redis/
    - sed -i '/export/d' ~/.bash_profile 
    - echo "PATH=\$PATH:/usr/local/redis/bin/" >> ~/.bash_profile 
    - echo "export PATH" >> ~/.bash_profile 
    - source ~/.bash_profile 


    