#  清除redis数据
- hosts: pms-redis
  remote_user: root
  tasks:
  - name: remove install redis file 
    file: 
      path: "{{ item }}"
      state: absent
    loop: 
      - /tmp/redis/
      - /usr/local/redis
      - /etc/redis
      - /opt/soft/redis/data
      - /var/log/redis 
  - name: "Recover .bash_profile."
    shell: "{{ item }}"
    loop: 
      - sed -i '/export/d' ~/.bash_profile 
      - sed -i '/redis/d' ~/.bash_profile 
      - echo "export PATH" >> ~/.bash_profile 
      - source ~/.bash_profile 
  # - name: install tools for redis
  #   yum:
  #     name: "{{ item }}"
  #     state: removed    # 删除软件
  #   loop:
  #     - gcc
  #     - automake
  #     - autoconf
  #     - libtool
  #     - make


      