#  清除redis数据
- hosts: pms-redis
  remote_user: root
  tasks:
  - name: remove install redis file 
    file: 
      path: "{{ item }}"
      state: absent
    loop: 
      - /tmp/redis/
      - /usr/local/redis
      - /etc/redis
      - /data
      - /var/log/redis 
      - /usr/local/bin/redis.sh
  - name: "Recover .bash_profile."
    shell: "{{ item }}"
    loop: 
      - sed -i '/export/d' ~/.bash_profile 
      - sed -i '/redis/d' ~/.bash_profile 
      - echo "export PATH" >> ~/.bash_profile 
      - source ~/.bash_profile 
      - ps -ef | grep redis-serve | grep -v grep | awk '{print $2}'|xargs --no-run-if-empty kill -9
      - ps -ef | grep redis-sentinel | grep -v grep | awk '{print $2}'|xargs --no-run-if-empty kill -9
  # - name: install tools for redis
  #   yum:
  #     name: "{{ item }}"
  #     state: removed    # 删除软件
  #   loop:
  #     - gcc
  #     - automake
  #     - autoconf
  #     - libtool
  #     - make

#  清除mysql数据
- hosts: pms-mysql
  remote_user: root
  tasks:
  - name: "remove mysql."
    shell: "{{ item }}"
    args:
      chdir: /tmp/mysql
    loop: 
      - ./mysql.sh   --b={{ MYSQL_BASE_PATH }}  --d={{ MYSQL_DATAPATH }} remove